import { StyleSheet } from "react-native";
export default StyleSheet.create({
  closeButton: {
    marginRight: 10,
    marginLeft: "auto",
  },
  circle: {
    height: 535,
    width: 546,
    backgroundColor: "#fff",
    top: "10%",
    borderRadius: 9000,
    shadowColor: "rgba(0, 0, 0, 0.8)",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowRadius: 30,
    alignSelf: "center",
  },
  headText: {
    fontSize: 36,
    fontWeight: 600,
    alignSelf: "center",
    position: "relative",
  },
  blockOfTextInput: {
    top: "18%",
    position: "relative",
    alignSelf: "center",
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderRadius: 10,
    borderColor: "#c0c3c4",
    width: "56%",
    height: "9%",
    justifyContent: "center",
    flexDirection: "row",
  },
  input: {
    position: "relative",
    flex: 1,
    height: "100%",
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    fontSize: 19,
    color: "#656565",
  },
  textUnderInput: {
    fontWeight: 600,
    alignSelf: "center",
    position: "relative",
    color: "#723fc6",
  },
  settupButton: {
    position: "relative",
    alignSelf: "center",
    top: "10%",
    backgroundColor: "#bf97ff",
    height: 42,
    borderColor: "#f8fdff",
    borderRadius: 20,
    elevation: 6,
  },
  textInSettupButton: {
    marginTop: 6,
    fontSize: 23,
    fontWeight: 600,
    color: "#fff",
    alignSelf: "center",
    position: "relative",
  },
  buttonUnderCircle: {
    marginTop: 40,
    position: "relative",
    alignSelf: "center",
    height: 30,
    top: "15%",
  },
  textUnderCircle: {
    alignSelf: "center",
    fontSize: 20,
    fontWeight: 600,
    color: "#723fc6",
  },
});
